spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: techdguide
    json:
      name: techdguide_json
  exchange:
      name: techdguide_exchange
  routing:
    key: techdguide_routing_key
    json:
      key: techdguide_routing_json_key